services:
  - type: web
    name: jay-kirana
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /profile
        destination: /index.html
      - type: rewrite
        source: /cart
        destination: /index.html
      - type: rewrite
        source: /checkout
        destination: /index.html
      - type: rewrite
        source: /forgot-password
        destination: /index.html
      - type: rewrite
        source: /reset-password
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    envVars:
      - key: VITE_API_URL
        value: https://jay-kirana-api.onrender.com 