services:
  - type: web
    name: jay-kirana
    env: node
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
    buildFilter:
      paths:
        - client/**
        - server/**
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /uploads/*
        destination: /uploads/$1
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable 