services:
  # API Service
  - type: web
    name: jay-kirana-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://jay-kirana.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
    
  # Client Service
  - type: static
    name: jay-kirana
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /api/*
        destination: https://jay-kirana-api.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://jay-kirana-api.onrender.com
      - key: VITE_UPLOAD_URL
        value: https://jay-kirana-api.onrender.com/uploads 