services:
  # Backend API service
  - type: web
    name: jay-kirana-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CLIENT_URL
        sync: false

  # Frontend static site
  - type: static
    name: jay-kirana-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://jay-kirana-api.onrender.com
      - key: VITE_UPLOAD_URL
        value: https://jay-kirana-api.onrender.com/uploads 